### ISSUE TITLE
mata v account off by 104.87 on the new application

### ISSUE THREAD

**Issue by Greg2314** [mattkbrat/autoflp-web#18]

**Comment by mattkbrat** [comment]
I believe that this is the difference between lien and finance. I will look into it and update some documentation if necessary.

**Comment by mattkbrat** [comment]
The old payment system worked by taking the full number of remaining months * the payment, but that created a difference from the last month.

![image](https://github.com/user-attachments/assets/7e57f749-833b-456b-82e6-b5868ab76100)
